"""updated default id vals to email verification token table

Revision ID: 3e3a9279e047
Revises: 807cffa7d256
Create Date: 2026-01-22 23:37:48.916872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3a9279e047'
down_revision: Union[str, Sequence[str], None] = '807cffa7d256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_verification_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verification_tokens', type_='unique')
    # ### end Alembic commands ###
