"""added username to the user table

Revision ID: 81167f2999a4
Revises: e104023d250d
Create Date: 2026-01-29 22:12:04.835424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81167f2999a4'
down_revision: Union[str, Sequence[str], None] = 'e104023d250d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'password_reset_tokens', ['id'])
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    # ### end Alembic commands ###
