services:
  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api-gateway
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - observability

    depends_on:
      - db

  api-provider:
    build:
      context: .
      dockerfile: api_provider/Dockerfile

    container_name: api-provider
    volumes:
      - .:/app

    ports:
      - "8002:8002"
    networks:
      - observability

    depends_on:
      - db

  upload-service:
    build:
      context: .
      dockerfile: upload_service/Dockerfile

    container_name: upload-service

    volumes:
      - .:/app

    ports:
      - "8001:8001"

    networks:
      - observability

    depends_on:
      - db
      - rabbitmq

  conversion-service:
    build:
      context: .
      dockerfile: conversion_workers/Dockerfile

    container_name: conversion-service

    depends_on:
      - db
      - rabbitmq

    networks:
      - observability

    volumes:
      - .:/app

  migration:
    build:
      context: .
      dockerfile: shared_database/Dockerfile

    env_file:
      - shared_database/.env

    container_name: migration
    volumes:
      - .:/app

    networks:
      - observability
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: charantm
      POSTGRES_PASSWORD: Charantm7
      POSTGRES_DB: docconvert
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - observability

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - observability

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

    networks:
      - observability

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

    networks:
      - observability

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    networks:
      - observability

volumes:
  postgres_data:
  redis_data:

networks:
  observability:
    external: true
