"""added download url in the jobs

Revision ID: 33e4e5075be4
Revises: 55346e8b7a14
Create Date: 2026-03-25 20:05:12.927078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e4e5075be4'
down_revision: Union[str, Sequence[str], None] = '55346e8b7a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dowload_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dowload_url')
    # ### end Alembic commands ###
