"""update jobs table

Revision ID: 490774c7c464
Revises: 33e4e5075be4
Create Date: 2026-03-26 09:16:49.507538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490774c7c464'
down_revision: Union[str, Sequence[str], None] = '33e4e5075be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retry', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_retry')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
