"""updated conversion type constraints jobs

Revision ID: 4db7013f6dd7
Revises: 5dbdfb27e7a0
Create Date: 2026-03-26 17:59:33.284109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db7013f6dd7'
down_revision: Union[str, Sequence[str], None] = '5dbdfb27e7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'conversion_type',
               existing_type=postgresql.ENUM('convert_pdf_to_ppt', 'convert_docx_to_pdf', 'convert_pdf_to_docx', 'compress_pdf', 'merge_pdf', name='job_conversion_type'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'conversion_type',
               existing_type=postgresql.ENUM('convert_pdf_to_ppt', 'convert_docx_to_pdf', 'convert_pdf_to_docx', 'compress_pdf', 'merge_pdf', name='job_conversion_type'),
               nullable=False)
    # ### end Alembic commands ###
