"""updated job tabel

Revision ID: 55346e8b7a14
Revises: 82d1d78c6d7d
Create Date: 2026-03-24 17:02:09.896146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55346e8b7a14'
down_revision: Union[str, Sequence[str], None] = '82d1d78c6d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('conversion_type', sa.Enum('convert_pdf_to_ppt', 'convert_docx_to_pdf',
                  'convert_pdf_to_docx', 'compress_pdf', 'merge_pdf', name='job_conversion_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'conversion_type')
    # ### end Alembic commands ###
