"""update the apikey table

Revision ID: 5824f957bc9b
Revises: 78d291e768d8
Create Date: 2026-03-04 15:34:56.904266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5824f957bc9b'
down_revision: Union[str, Sequence[str], None] = '78d291e768d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hashed_key', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expiring_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    op.create_index(op.f('ix_api_key_prefix'), 'api_key', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'email_verification_tokens', ['id'])
    op.create_unique_constraint(None, 'password_reset_tokens', ['id'])
    op.create_unique_constraint(None, 'refresh_token', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_constraint(None, 'email_verification_tokens', type_='unique')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_prefix'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
