"""updated output url jobs

Revision ID: 5dbdfb27e7a0
Revises: a9aeaabc8ff9
Create Date: 2026-03-26 17:46:06.285777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbdfb27e7a0'
down_revision: Union[str, Sequence[str], None] = 'a9aeaabc8ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('upload_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'upload_url')
    # ### end Alembic commands ###
