"""docker migration

Revision ID: 67bcb100de6e
Revises: 5824f957bc9b
Create Date: 2026-03-10 14:02:06.257176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bcb100de6e'
down_revision: Union[str, Sequence[str], None] = '5824f957bc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'scopes')
    # ### end Alembic commands ###
