"""added subs plan 1

Revision ID: 7721f3765f10
Revises: 67bcb100de6e
Create Date: 2026-03-11 10:01:25.669740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7721f3765f10'
down_revision: Union[str, Sequence[str], None] = '67bcb100de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subscription_plan = sa.Enum(
    "free",
    "pro",
    "enterprise",
    name="subscriptionplan"
)

def upgrade() -> None:
    """Upgrade schema."""
    subscription_plan.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', subscription_plan, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    subscription_plan.drop(op.get_bind())
    # ### end Alembic commands ###
