"""updated input url jobs

Revision ID: a9aeaabc8ff9
Revises: 490774c7c464
Create Date: 2026-03-26 17:38:50.134979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9aeaabc8ff9'
down_revision: Union[str, Sequence[str], None] = '490774c7c464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'input_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'input_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
